Simplify outdate documentation
MEN-Mikro-Elektronik/13Z055-90 pull request #13
Opened 2023-03-21 11:39 UTC by mad-jsanjuan

Remove references to old methods for compiling these components agains older linux kernels and ELINOS projects.

Keep useful stuff but remove things that may lead to confusing documentation and may get outdated by third parties (installing other tools).

2023-03-23 08:45 UTC, mad-jrodriguez approved these changes

2023-03-23 13:21 UTC, ckloecker requested changes

2023-03-23 13:21 UTC, ckloecker commented on DRIVERS/Z055_HDLC/README.md
> +driver creates should contain an entire HDLC frame. Including
No, not "an entire HDLC frame" as the driver takes care of the flags and checksum. Rather:

The z055_hdlc_drv driver takes the HDLC address and control bytes from the beginning of each data package that is written to the tty device. So all packages written to the tty device should contain those bytes. For example, "echo -ne '\x13\x37Hello world!' > /dev/ttyTH0" will embed "Hello world!" in an HDLC package with address 0x13 and control 0x37.

2023-03-23 13:21 UTC, ckloecker commented on DRIVERS/Z055_HDLC/README.md
> +These Z055 HDLC drivers and tools shall be built inside a MDIS
```suggestion
These Z055 HDLC drivers and tools shall be built inside an MDIS
```

2023-03-23 13:21 UTC, ckloecker commented on DRIVERS/Z055_HDLC/README.md
> +Project from the parent component 13MD05-90.
```suggestion
project from the parent component 13MD05-90.
```

2023-03-23 13:21 UTC, ckloecker commented on DRIVERS/Z055_HDLC/README.md
FIXME: README.md still references README.PPP that has been renamed to PPP.md!

2023-03-23 13:21 UTC, ckloecker commented on DRIVERS/Z055_HDLC/PPP.md
>  --------------------------
```suggestion
--------------------
```

2023-03-23 13:21 UTC, ckloecker commented on DRIVERS/Z055_HDLC/PPP.md
>  --------------------------
```suggestion
--------------------
```

2023-03-23 15:34 UTC, mad-jsanjuan commented
@ckloecker Thanks for the review. I have addressed the issues you pointed out.

2023-03-27 09:29 UTC, ckloecker commented on DRIVERS/Z055_HDLC/README.md
> +the beggining of the frame and then the data payload. The checksum
```suggestion
the beginning of the frame and then the data payload. The checksum
```

2023-03-28 07:08 UTC, merged